### ISSUE TITLE
Test with renode fails for CMSIS with target STM32L476

### ISSUE THREAD

**Issue by GeoBouz** [iml130/iree-bare-metal-arm#322]
Hello!
Although the build and the renode test is done successfully for the target STM32F407, when I do the build and test with renode for the STM32L476 target the build is done successfuly but when I test with renode I get the error below:
19:01:35.7345 [WARNING] sysbus: [cpu: 0x0] ReadByte from non existing peripheral at 0x0.
19:01:35.7346 [ERROR] cpu: CPU abort [PC=0x0]: Trying to execute code outside RAM or ROM at 0x00000000.

The target is build with this:
cmake -GNinja \
    -DBUILD_WITH_CMSIS=ON \
    -DCMAKE_TOOLCHAIN_FILE="realpath/iree-bare-metal-arm/build_tools/cmake/arm-none-eabi-gcc.cmake" \
    -DARM_TOOLCHAIN_ROOT="realpath/opt/gcc-arm-none-eabi" \
    -DARM_CPU="cortex-m4" \
    -DARM_TARGET="STM32L476" \
    -DIREE_ERROR_ON_MISSING_SUBMODULES=OFF \
    -DIREE_HAL_DRIVER_LOCAL_SYNC=ON \
    -DIREE_HAL_EXECUTABLE_LOADER_EMBEDDED_ELF=ON \
    -DIREE_HAL_EXECUTABLE_LOADER_VMVX_MODULE=ON \
    -DIREE_HOST_BIN_DIR="/realpath/iree-bare-metal-arm/build-iree-host-install/bin" \
    -DCUSTOM_ARM_LINKER_FLAGS="" \
    -DLINKER_SCRIPT="realpath/iree-bare-metal-arm/build_tools/stm32l476xg-cmsis.ld" \
    -DUSE_UART2=ON \
    ..
cmake --build . --target sample_vmvx_sync

then I started renode and included resc file and loaded the elf file.
(monitor) include @/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/renode/stm32l476.resc
(STM32F407) sysbus LoadELF @/home/gbouzikas/Thesis/iree-bare-metal-arm/build/samples/simple_embedding/sample_vmvx_sync.elf
(STM32F407) start

And then I get this:

Starting emulation...
19:01:35.6314 [INFO] cpu: Guessing VectorTableOffset value to be 0x8000000.
19:01:35.6344 [INFO] cpu: Setting initial values: PC = 0x8071C4D, SP = 0x20018000.
19:01:35.6357 [INFO] STM32L476: Machine started.
19:01:35.7111 [INFO] usart2: [host: 9.44s (+9.44s)|virt: 0.2ms (+0.2ms)] Running simple_embedding...
19:01:35.7345 [WARNING] sysbus: [cpu: 0x0] ReadByte from non existing peripheral at 0x0.
19:01:35.7346 [ERROR] cpu: CPU abort [PC=0x0]: Trying to execute code outside RAM or ROM at 0x00000000.

**Comment by marbre** [comment]
When building the sample with our helper script `build_tools/configure_build.sh` and passing `cmsis stm32l476` as options, the samples run as expected with Renode 1.14.0:
```
(monitor) include @../repos/iree-bare-metal-arm/third_party/renode/stm32l476.resc
[..]
(STM32L476) sysbus LoadELF @../repos/iree-bare-metal-arm/build/samples/simple_embedding/sample_vmvx_sync.elf 
[..]
(STM32L476) start
Starting emulation...
19:48:17.2500 [INFO] cpu: Guessing VectorTableOffset value to be 0x8000000.
19:48:17.2516 [INFO] cpu: Setting initial values: PC = 0x8013681, SP = 0x20018000.
19:48:17.2521 [INFO] STM32L476: Machine started.
19:48:17.2586 [INFO] usart2: [host: 16.14s (+16.14s)|virt: 0.1ms (+0.1ms)] Running simple_embedding...
19:48:17.2851 [INFO] usart2: [host: 16.17s (+26.46ms)|virt: 1.3ms (+1.2ms)] [[ iree_hal_allocator_t memory statistics ]]
19:48:17.2855 [INFO] usart2: [host:  16.17s (+0.46ms)|virt:    1.3ms (+0s)]   HOST_LOCAL:            0B peak /            0B allocated /            0B freed /            0B live
19:48:17.2859 [INFO] usart2: [host:  16.17s (+0.42ms)|virt:    1.3ms (+0s)] DEVICE_LOCAL:           48B peak /           48B allocated /            0B freed /           48B live
19:48:17.2876 [INFO] usart2: [host:  16.17s (+1.65ms)|virt: 1.4ms (+0.1ms)] Execution successful!
19:48:17.2876 [INFO] usart2: [host:  16.17s (+0.13ms)|virt:    1.4ms (+0s)] simple_embedding done
```

At a first very quick glance, the CMake arguments look right. What commit are you trying the build, what toolchain do you use and what Renose version was used for testing?

**Comment by GeoBouz** [comment]
The toolchain that I am using is arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi and the renode version is 1.14.0.29506.
About the commit it is this:
commit a7982e4b8df193bf7ea959e04c1395ffac405a4d (HEAD -> main, origin/main, origin/HEAD)
Author: Marius Brehler <marius.brehler@iml.fraunhofer.de>
Date:   Wed Feb 28 17:10:42 2024 +0100

    Integrate IREE at openxla/iree@5d8907e (#321)
    
    Updates IREE usage to match openxla/iree@5d8907e and
    candidate-20240222.809, respectively.

**Comment by marbre** [comment]
I just compared the build options you specified with those in the script we're using by default. The main difference is that we build a `MinSizeRel`, while a `Release` is build by default if not specifying the `CMAKE_BUILD_TYPE`. If no idea yet why the executable fails with a `Release` build, but I assume you could switch to a `MinSizeRel`?

**Comment by GeoBouz** [comment]
I switched to MinSizeRel and tried with tconfigure_build.sh but when I try to run cmake --build . --target sample_vmvx_sync I get this error:
FAILED: samples/simple_embedding/CMakeFiles/sample_vmvx_sync.dir/simple_embedding_float.c.obj 
/home/gbouzikas/Thesis/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -DFLATCC_USE_GENERIC_ALIGNED_ALLOC -DIREE_HAVE_HAL_EXECUTABLE_LOADER_VMVX_MODULE=1 -DIREE_HAVE_VMVX_MODULE -DIREE_PLATFORM_GENERIC -DIREE_STATUS_FEATURES=0 -DIREE_SYNCHRONIZATION_DISABLE_UNSAFE=1 -DSTM32F407xx -I/home/gbouzikas/Thesis/iree-bare-metal-arm/build/samples/simple_embedding -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/cmsis_device_f4/Include -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/CMSIS_5/CMSIS/Core/Include -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/.. -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree/runtime/src/iree/.. -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree/runtime/src/iree/base/internal/flatcc -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/third_party/flatcc/include -isystem /home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree/runtime/src/iree/schemas -mthumb -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DIREE_TIME_NOW_FN="{ return 0; }" -DIREE_WAIT_UNTIL_FN=wait_until -Wl,--gc-sections -ffunction-sections -fdata-sections  -Wno-char-subscripts -Wno-format -Wno-implicit-function-declaration -Wno-unused-variable -Os -DNDEBUG -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/third_party/flatcc/include/ -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/third_party/flatcc/include/flatcc/reflection/ -MD -MT samples/simple_embedding/CMakeFiles/sample_vmvx_sync.dir/simple_embedding_float.c.obj -MF samples/simple_embedding/CMakeFiles/sample_vmvx_sync.dir/simple_embedding_float.c.obj.d -o samples/simple_embedding/CMakeFiles/sample_vmvx_sync.dir/simple_embedding_float.c.obj -c /home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c
In file included from /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/allocator.h:17,
                 from /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/api.h:82,
                 from /home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:17:
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c: In function 'Run':
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:44:34: warning: passing argument 2 of 'iree_hal_module_create' makes pointer from integer without a cast [-Wint-conversion]
   44 |       instance, /*device_count=*/1, &device, IREE_HAL_MODULE_FLAG_SYNCHRONOUS,
      |                                  ^
      |                                  |
      |                                  int
In file included from /home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:19:
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/modules/hal/module.h:33:54: note: expected 'iree_hal_device_t *' {aka 'struct iree_hal_device_t *'} but argument is of type 'int'
   33 |     iree_vm_instance_t* instance, iree_hal_device_t* device,
      |                                   ~~~~~~~~~~~~~~~~~~~^~~~~~
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:44:37: warning: passing argument 3 of 'iree_hal_module_create' makes integer from pointer without a cast [-Wint-conversion]
   44 |       instance, /*device_count=*/1, &device, IREE_HAL_MODULE_FLAG_SYNCHRONOUS,
      |                                     ^~~~~~~
      |                                     |
      |                                     iree_hal_device_t ** {aka struct iree_hal_device_t **}
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/modules/hal/module.h:34:29: note: expected 'iree_hal_module_flags_t' {aka 'long unsigned int'} but argument is of type 'iree_hal_device_t **' {aka 'struct iree_hal_device_t **'}
   34 |     iree_hal_module_flags_t flags, iree_allocator_t host_allocator,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:44:46: error: incompatible type for argument 4 of 'iree_hal_module_create'
   44 |       instance, /*device_count=*/1, &device, IREE_HAL_MODULE_FLAG_SYNCHRONOUS,
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              |
      |                                              int
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/modules/hal/module.h:34:53: note: expected 'iree_allocator_t' {aka 'struct iree_allocator_t'} but argument is of type 'int'
   34 |     iree_hal_module_flags_t flags, iree_allocator_t host_allocator,
      |                                    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:45:7: error: incompatible type for argument 5 of 'iree_hal_module_create'
   45 |       iree_allocator_system(), &hal_module));
      |       ^~~~~~~~~~~~~~~~~~~~~~~
      |       |
      |       iree_allocator_t {aka struct iree_allocator_t}
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/modules/hal/module.h:35:24: note: expected 'iree_vm_module_t **' {aka 'struct iree_vm_module_t **'} but argument is of type 'iree_allocator_t' {aka 'struct iree_allocator_t'}
   35 |     iree_vm_module_t** out_module);
      |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
/home/gbouzikas/Thesis/iree-bare-metal-arm/samples/simple_embedding/simple_embedding_float.c:43:24: error: too many arguments to function 'iree_hal_module_create'
   43 |   IREE_RETURN_IF_ERROR(iree_hal_module_create(
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/modules/hal/module.h:32:31: note: declared here
   32 | IREE_API_EXPORT iree_status_t iree_hal_module_create(

Is ther an issue with my simple_embedding_float.c file because I see an error in the line mentioned in the fail output?

<img width="630" alt="image" src="https://github.com/iml130/iree-bare-metal-arm/assets/32775657/fe48dd4a-6027-48fb-b6d3-68e6ba42caa8">

**Comment by marbre** [comment]
Seems like the IREE submodule you checked out does not match the version integrated into iree-bare-metal-arm. For example, if you're still trying to build commit a7982e4b8df193bf7ea959e04c1395ffac405a4d, make sure that the IREE submodule points to commit openxla/iree@5d8907e.

**Comment by GeoBouz** [comment]
You are right! I pulled the latest changes of the IREE and now I didnt get the error. Thank you! 

Last thing I ask is that now that I run it i get NOT_FOUND on the output:

09:54:48.2004 [INFO] cpu: Guessing VectorTableOffset value to be 0x8000000.
09:54:48.2038 [INFO] cpu: Setting initial values: PC = 0x8013681, SP = 0x20018000.
09:54:48.2050 [INFO] STM32L476: Machine started.
09:54:48.2846 [INFO] usart2: [host: 5.96s (+5.96s)|virt: 0.1ms (+0.1ms)] Running simple_embedding...
09:54:48.2899 [INFO] usart2: [host: 5.97s (+5.43ms)|virt: 0.5ms (+0.4ms)] NOT_FOUND
09:54:48.2902 [INFO] usart2: [host: 5.97s (+0.22ms)|virt:    0.5ms (+0s)] simple_embedding done

I made the build with configure_build.sh cmsis stm32l476

**Comment by marbre** [comment]
I guess you build with `IREE_STATUS_FEATURES` disabled. If building with status features the output should be:

```
09:17:35.6907 [INFO] STM32L476: Machine started.
09:17:35.7091 [INFO] usart2: [host: 2.76s (+2.76s)|virt: 0.1ms (+0.1ms)] Running simple_embeddin
09:17:35.7420 [INFO] usart2: [host: 2.8s (+33.07ms)|virt: 1.3ms (+1.2ms)] [[ iree_hal_allocator_
09:17:35.7423 [INFO] usart2: [host:  2.8s (+0.39ms)|virt:    1.3ms (+0s)]   HOST_LOCAL:         
09:17:35.7427 [INFO] usart2: [host:  2.8s (+0.39ms)|virt:    1.3ms (+0s)] DEVICE_LOCAL:         
09:17:35.7443 [INFO] usart2: [host:  2.8s (+1.57ms)|virt: 1.4ms (+0.1ms)] Execution successful!
09:17:35.7444 [INFO] usart2: [host:  2.8s (+0.14ms)|virt:    1.4ms (+0s)] simple_embedding done
```

**Comment by GeoBouz** [comment]
I enabled it on the CMakeLists.txt (add_compile_definitions(IREE_STATUS_FEATURES=1)) and when I try to build with cmake --build . --target sample_vmvx_sync I get this error: 
FAILED: third_party/iree/runtime/src/iree/base/CMakeFiles/iree_base_base.objects.dir/status.c.obj 
/home/gbouzikas/Thesis/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc -DFLATCC_USE_GENERIC_ALIGNED_ALLOC -DIREE_PLATFORM_GENERIC -DIREE_STATUS_FEATURES=1 -DIREE_SYNCHRONIZATION_DISABLE_UNSAFE=1 -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree -I/home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree -I/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src -I/home/gbouzikas/Thesis/iree-bare-metal-arm/build/third_party/iree/runtime/src -mthumb -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DIREE_TIME_NOW_FN="{ return 0; }" -DIREE_WAIT_UNTIL_FN=wait_until -Wl,--gc-sections -ffunction-sections -fdata-sections  -Wno-char-subscripts -Wno-format -Wno-implicit-function-declaration -Wno-unused-variable -fPIC -fvisibility=hidden -Wall -Werror -Wno-error=deprecated-declarations -Wno-address -Wno-address-of-packed-member -Wno-comment -Wno-format-zero-length -Wno-uninitialized -Wno-pointer-sign -Wno-sign-compare -Wno-unused-function -Wno-unknown-pragmas -fmacro-prefix-map=/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree=iree -std=gnu11 -MD -MT third_party/iree/runtime/src/iree/base/CMakeFiles/iree_base_base.objects.dir/status.c.obj -MF third_party/iree/runtime/src/iree/base/CMakeFiles/iree_base_base.objects.dir/status.c.obj.d -o third_party/iree/runtime/src/iree/base/CMakeFiles/iree_base_base.objects.dir/status.c.obj -c /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/status.c
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/status.c: In function 'iree_status_freeze':
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/status.c:1249:14: error: 'iree_status_storage_t' has no member named 'message'
 1249 |   new_storage->message.size = message_buffer_size - 1;
      |              ^~
/home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/runtime/src/iree/base/status.c:1250:14: error: 'iree_status_storage_t' has no member named 'message'
 1250 |   new_storage->message.data =
      |              ^~
[26/134] Building C object third_party/iree/runtime/src/iree/builtins/ukernel/CMakeFiles/iree_builtins_ukernel_ukernel.objects.dir/pack.c.obj
ninja: build stopped: subcommand failed.

**Comment by GeoBouz** [comment]
I started from the start and now it works now as expected. Thank you very much!!
